import "server-only";
import { prisma } from "@/lib/prisma";
import { getLedgerFinancialStatements } from "@/application/accounting/financial-statements-service";

export async function runStatementAgent(input:{organizationId:string;legalEntityId:string;fiscalPeriodId:string;actorId:string;correlationId:string}){
 const definition=await prisma.agentDefinition.upsert({where:{agentId:"planora-statement-agent"},create:{agentId:"planora-statement-agent",displayName:"Statement Agent",purpose:"Validate chart-of-accounts alignment and financial statement controls.",persona:"Evidence-first financial reporting controller",authorityClass:"A1_RECOMMEND",allowedTools:["ledger.read","chart-of-accounts.read","statement.calculate"],forbiddenActions:["journal.post","period.close","account.write","financial.write"],requiredContext:["organizationId","legalEntityId","fiscalPeriodId"],workflowStates:[],humanApprovalRequired:true,financialWritePermission:false,retryPolicy:{maxAttempts:1},memoryPolicy:{persist:"evidence-only"},learningPolicy:{humanFeedback:true},failurePolicy:{failClosed:true},auditPolicy:{evidenceRequired:true}},update:{authorityClass:"A1_RECOMMEND",financialWritePermission:false,humanApprovalRequired:true},select:{id:true,killSwitch:true}});
 if(definition.killSwitch!=="ENABLED") throw new Error("STATEMENT_AGENT_DISABLED");
 const statements=await getLedgerFinancialStatements(input.organizationId,{legalEntityId:input.legalEntityId,fiscalPeriodId:input.fiscalPeriodId});
 const run=await prisma.agentRun.create({data:{agentDefinitionId:definition.id,organizationId:input.organizationId,actorId:input.actorId,trigger:"LEDGER_STATEMENT_REVIEW",task:"Validate chart of accounts to P&L, balance sheet, and cash flow alignment",inputReferences:{legalEntityId:input.legalEntityId,fiscalPeriodId:input.fiscalPeriodId},toolTrace:[],evidence:{...statements.controls,...statements.coaControl},status:"RUNNING"}});
 const allPassed=statements.controls.trialBalanceBalanced&&statements.controls.balanceSheetBalanced&&statements.controls.cashFlowClassified&&statements.coaControl.mapped;
 const rec=await prisma.agentRecommendation.create({data:{runId:run.id,organizationId:input.organizationId,actorId:input.actorId,type:"FINANCIAL_STATEMENT_REVIEW",summary:allPassed?"COA mapping and ledger statements passed structural controls. Human review remains required.":"COA or financial statement controls require human review before downstream reliance.",observedFacts:{...statements.controls,...statements.coaControl},evidence:{correlationId:input.correlationId,legalEntityId:input.legalEntityId,fiscalPeriodId:input.fiscalPeriodId,currencyCode:statements.currencyCode},unsupportedClaim:false,status:"PENDING"}});
 await prisma.agentRun.update({where:{id:run.id},data:{status:"SUCCEEDED",completedAt:new Date(),output:{recommendationId:rec.id,decision:"RECOMMEND_STATEMENT_REVIEW"}}});
 return {recommendationId:rec.id,controls:{...statements.controls,coaMapped:statements.coaControl.mapped}};
}
