-- Generated by scripts/generate-tenant-rls.mjs. No data deletion or role creation.
-- The migration owner has an explicit maintenance policy. Runtime must be a
-- distinct non-owner role with NOINHERIT/NOBYPASSRLS, with no membership in owner.
BEGIN;
CREATE FUNCTION planora_session_tenant() RETURNS uuid
LANGUAGE sql STABLE SECURITY DEFINER
AS $function$
 SELECT m."organizationId" FROM "Session" s
 JOIN "User" u ON u.id=s."userId"
 JOIN "OrganizationMembership" m ON m.id=s."membershipId" AND m."userId"=s."userId"
 JOIN "Organization" o ON o.id=m."organizationId"
 WHERE s."tokenHash"=NULLIF(current_setting('planora.session_hash', true),'')
 AND s."expiresAt">CURRENT_TIMESTAMP AND u.active AND m.active AND o.active
 AND m.role IN ('CFO','FPA_DIRECTOR','ANALYST')
 LIMIT 1
$function$;
-- Bind lookup to the deployment schema, never a caller-controlled search_path.
DO $block$ BEGIN
 EXECUTE format('ALTER FUNCTION planora_session_tenant() SET search_path = %I, pg_catalog', current_schema());
END $block$;
REVOKE ALL ON FUNCTION planora_session_tenant() FROM PUBLIC;


ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Organization" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "Organization" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "Organization" USING ("id" = planora_session_tenant()) WITH CHECK (("id" = planora_session_tenant()));

ALTER TABLE "ExcelWorkbook" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExcelWorkbook" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ExcelWorkbook" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ExcelWorkbook" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("ExcelWorkbook"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="ExcelWorkbook"."organizationId"))));

ALTER TABLE "WorkbookProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkbookProfile" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "WorkbookProfile" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "WorkbookProfile" USING (EXISTS (SELECT 1 FROM "ExcelWorkbook" p WHERE p.id="WorkbookProfile"."workbookId")) WITH CHECK ((EXISTS (SELECT 1 FROM "ExcelWorkbook" p WHERE p.id="WorkbookProfile"."workbookId")) AND (("WorkbookProfile"."workbookId" IS NULL OR EXISTS (SELECT 1 FROM "ExcelWorkbook" r WHERE r."id"="WorkbookProfile"."workbookId"))));

ALTER TABLE "MappingTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MappingTemplate" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "MappingTemplate" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "MappingTemplate" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("MappingTemplate"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="MappingTemplate"."organizationId"))));

ALTER TABLE "MappingVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MappingVersion" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "MappingVersion" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "MappingVersion" USING (EXISTS (SELECT 1 FROM "MappingTemplate" p WHERE p.id="MappingVersion"."templateId")) WITH CHECK ((EXISTS (SELECT 1 FROM "MappingTemplate" p WHERE p.id="MappingVersion"."templateId")) AND (("MappingVersion"."templateId" IS NULL OR EXISTS (SELECT 1 FROM "MappingTemplate" r WHERE r."id"="MappingVersion"."templateId"))) AND (("MappingVersion"."workbookId" IS NULL OR EXISTS (SELECT 1 FROM "ExcelWorkbook" r WHERE r."id"="MappingVersion"."workbookId"))));

ALTER TABLE "MappingRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MappingRule" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "MappingRule" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "MappingRule" USING (EXISTS (SELECT 1 FROM "MappingVersion" p WHERE p.id="MappingRule"."mappingVersionId")) WITH CHECK ((EXISTS (SELECT 1 FROM "MappingVersion" p WHERE p.id="MappingRule"."mappingVersionId")) AND (("MappingRule"."mappingVersionId" IS NULL OR EXISTS (SELECT 1 FROM "MappingVersion" r WHERE r."id"="MappingRule"."mappingVersionId"))));

ALTER TABLE "MappingSuggestion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MappingSuggestion" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "MappingSuggestion" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "MappingSuggestion" USING (EXISTS (SELECT 1 FROM "MappingVersion" p WHERE p.id="MappingSuggestion"."mappingVersionId")) WITH CHECK ((EXISTS (SELECT 1 FROM "MappingVersion" p WHERE p.id="MappingSuggestion"."mappingVersionId")) AND (("MappingSuggestion"."mappingVersionId" IS NULL OR EXISTS (SELECT 1 FROM "MappingVersion" r WHERE r."id"="MappingSuggestion"."mappingVersionId"))));

ALTER TABLE "MappingDecision" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MappingDecision" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "MappingDecision" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "MappingDecision" USING (EXISTS (SELECT 1 FROM "MappingSuggestion" p WHERE p.id="MappingDecision"."suggestionId")) WITH CHECK ((EXISTS (SELECT 1 FROM "MappingSuggestion" p WHERE p.id="MappingDecision"."suggestionId")) AND (("MappingDecision"."suggestionId" IS NULL OR EXISTS (SELECT 1 FROM "MappingSuggestion" r WHERE r."id"="MappingDecision"."suggestionId"))));

ALTER TABLE "ImportBatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImportBatch" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ImportBatch" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ImportBatch" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("ImportBatch"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="ImportBatch"."organizationId"))) AND (("ImportBatch"."workbookId" IS NULL OR EXISTS (SELECT 1 FROM "ExcelWorkbook" r WHERE r."id"="ImportBatch"."workbookId"))) AND (("ImportBatch"."mappingVersionId" IS NULL OR EXISTS (SELECT 1 FROM "MappingVersion" r WHERE r."id"="ImportBatch"."mappingVersionId"))));

ALTER TABLE "ImportError" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImportError" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ImportError" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ImportError" USING (EXISTS (SELECT 1 FROM "ImportBatch" p WHERE p.id="ImportError"."importBatchId")) WITH CHECK ((EXISTS (SELECT 1 FROM "ImportBatch" p WHERE p.id="ImportError"."importBatchId")) AND (("ImportError"."importBatchId" IS NULL OR EXISTS (SELECT 1 FROM "ImportBatch" r WHERE r."id"="ImportError"."importBatchId"))));

ALTER TABLE "LegalEntity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LegalEntity" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "LegalEntity" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "LegalEntity" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("LegalEntity"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="LegalEntity"."organizationId"))));

ALTER TABLE "BusinessUnit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BusinessUnit" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "BusinessUnit" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "BusinessUnit" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("BusinessUnit"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="BusinessUnit"."organizationId"))));

ALTER TABLE "Geography" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Geography" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "Geography" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "Geography" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("Geography"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="Geography"."organizationId"))));

ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "Product" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "Product" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("Product"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="Product"."organizationId"))));

ALTER TABLE "Customer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "Customer" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "Customer" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("Customer"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="Customer"."organizationId"))));

ALTER TABLE "CostCenter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CostCenter" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "CostCenter" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "CostCenter" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("CostCenter"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="CostCenter"."organizationId"))));

ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "Account" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "Account" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("Account"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="Account"."organizationId"))));

ALTER TABLE "FiscalCalendar" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FiscalCalendar" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "FiscalCalendar" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "FiscalCalendar" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("FiscalCalendar"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="FiscalCalendar"."organizationId"))));

ALTER TABLE "FiscalYear" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FiscalYear" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "FiscalYear" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "FiscalYear" USING (EXISTS (SELECT 1 FROM "FiscalCalendar" p WHERE p.id="FiscalYear"."fiscalCalendarId")) WITH CHECK ((EXISTS (SELECT 1 FROM "FiscalCalendar" p WHERE p.id="FiscalYear"."fiscalCalendarId")) AND (("FiscalYear"."fiscalCalendarId" IS NULL OR EXISTS (SELECT 1 FROM "FiscalCalendar" r WHERE r."id"="FiscalYear"."fiscalCalendarId"))));

ALTER TABLE "FiscalPeriod" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FiscalPeriod" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "FiscalPeriod" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "FiscalPeriod" USING (EXISTS (SELECT 1 FROM "FiscalYear" p WHERE p.id="FiscalPeriod"."fiscalYearId")) WITH CHECK ((EXISTS (SELECT 1 FROM "FiscalYear" p WHERE p.id="FiscalPeriod"."fiscalYearId")) AND (("FiscalPeriod"."fiscalYearId" IS NULL OR EXISTS (SELECT 1 FROM "FiscalYear" r WHERE r."id"="FiscalPeriod"."fiscalYearId"))));

ALTER TABLE "FinancialFact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FinancialFact" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "FinancialFact" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "FinancialFact" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("FinancialFact"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="FinancialFact"."organizationId"))) AND (("FinancialFact"."accountId" IS NULL OR EXISTS (SELECT 1 FROM "Account" r WHERE r."id"="FinancialFact"."accountId"))) AND (("FinancialFact"."fiscalPeriodId" IS NULL OR EXISTS (SELECT 1 FROM "FiscalPeriod" r WHERE r."id"="FinancialFact"."fiscalPeriodId"))) AND (("FinancialFact"."legalEntityId" IS NULL OR EXISTS (SELECT 1 FROM "LegalEntity" r WHERE r."id"="FinancialFact"."legalEntityId"))) AND (("FinancialFact"."businessUnitId" IS NULL OR EXISTS (SELECT 1 FROM "BusinessUnit" r WHERE r."id"="FinancialFact"."businessUnitId"))) AND (("FinancialFact"."geographyId" IS NULL OR EXISTS (SELECT 1 FROM "Geography" r WHERE r."id"="FinancialFact"."geographyId"))) AND (("FinancialFact"."productId" IS NULL OR EXISTS (SELECT 1 FROM "Product" r WHERE r."id"="FinancialFact"."productId"))) AND (("FinancialFact"."customerId" IS NULL OR EXISTS (SELECT 1 FROM "Customer" r WHERE r."id"="FinancialFact"."customerId"))) AND (("FinancialFact"."costCenterId" IS NULL OR EXISTS (SELECT 1 FROM "CostCenter" r WHERE r."id"="FinancialFact"."costCenterId"))));

ALTER TABLE "LineageReference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LineageReference" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "LineageReference" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "LineageReference" USING (EXISTS (SELECT 1 FROM "FinancialFact" p WHERE p.id="LineageReference"."financialFactId")) WITH CHECK ((EXISTS (SELECT 1 FROM "FinancialFact" p WHERE p.id="LineageReference"."financialFactId")) AND (("LineageReference"."financialFactId" IS NULL OR EXISTS (SELECT 1 FROM "FinancialFact" r WHERE r."id"="LineageReference"."financialFactId"))));

ALTER TABLE "MetricDefinition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MetricDefinition" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "MetricDefinition" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "MetricDefinition" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("MetricDefinition"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="MetricDefinition"."organizationId"))));

ALTER TABLE "CalculationDefinition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CalculationDefinition" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "CalculationDefinition" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "CalculationDefinition" USING (EXISTS (SELECT 1 FROM "MetricDefinition" p WHERE p.id="CalculationDefinition"."metricDefinitionId")) WITH CHECK ((EXISTS (SELECT 1 FROM "MetricDefinition" p WHERE p.id="CalculationDefinition"."metricDefinitionId")) AND (("CalculationDefinition"."metricDefinitionId" IS NULL OR EXISTS (SELECT 1 FROM "MetricDefinition" r WHERE r."id"="CalculationDefinition"."metricDefinitionId"))));

ALTER TABLE "MetricDependency" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MetricDependency" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "MetricDependency" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "MetricDependency" USING (EXISTS (SELECT 1 FROM "MetricDefinition" p WHERE p.id="MetricDependency"."metricDefinitionId")) WITH CHECK ((EXISTS (SELECT 1 FROM "MetricDefinition" p WHERE p.id="MetricDependency"."metricDefinitionId")) AND (("MetricDependency"."metricDefinitionId" IS NULL OR EXISTS (SELECT 1 FROM "MetricDefinition" r WHERE r."id"="MetricDependency"."metricDefinitionId"))) AND (("MetricDependency"."dependsOnMetricId" IS NULL OR EXISTS (SELECT 1 FROM "MetricDefinition" r WHERE r."id"="MetricDependency"."dependsOnMetricId"))));

ALTER TABLE "MetricValue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MetricValue" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "MetricValue" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "MetricValue" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("MetricValue"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="MetricValue"."organizationId"))) AND (("MetricValue"."metricDefinitionId" IS NULL OR EXISTS (SELECT 1 FROM "MetricDefinition" r WHERE r."id"="MetricValue"."metricDefinitionId"))) AND (("MetricValue"."fiscalPeriodId" IS NULL OR EXISTS (SELECT 1 FROM "FiscalPeriod" r WHERE r."id"="MetricValue"."fiscalPeriodId"))));

ALTER TABLE "Plan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Plan" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "Plan" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "Plan" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("Plan"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="Plan"."organizationId"))));

ALTER TABLE "PlanVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlanVersion" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "PlanVersion" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "PlanVersion" USING (EXISTS (SELECT 1 FROM "Plan" p WHERE p.id="PlanVersion"."planId")) WITH CHECK ((EXISTS (SELECT 1 FROM "Plan" p WHERE p.id="PlanVersion"."planId")) AND (("PlanVersion"."planId" IS NULL OR EXISTS (SELECT 1 FROM "Plan" r WHERE r."id"="PlanVersion"."planId"))));

ALTER TABLE "Forecast" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Forecast" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "Forecast" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "Forecast" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("Forecast"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="Forecast"."organizationId"))));

ALTER TABLE "ForecastVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ForecastVersion" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ForecastVersion" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ForecastVersion" USING (EXISTS (SELECT 1 FROM "Forecast" p WHERE p.id="ForecastVersion"."forecastId")) WITH CHECK ((EXISTS (SELECT 1 FROM "Forecast" p WHERE p.id="ForecastVersion"."forecastId")) AND (("ForecastVersion"."forecastId" IS NULL OR EXISTS (SELECT 1 FROM "Forecast" r WHERE r."id"="ForecastVersion"."forecastId"))));

ALTER TABLE "ForecastLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ForecastLine" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ForecastLine" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ForecastLine" USING (EXISTS (SELECT 1 FROM "ForecastVersion" p WHERE p.id="ForecastLine"."forecastVersionId")) WITH CHECK ((EXISTS (SELECT 1 FROM "ForecastVersion" p WHERE p.id="ForecastLine"."forecastVersionId")) AND (("ForecastLine"."forecastVersionId" IS NULL OR EXISTS (SELECT 1 FROM "ForecastVersion" r WHERE r."id"="ForecastLine"."forecastVersionId"))) AND (("ForecastLine"."accountId" IS NULL OR EXISTS (SELECT 1 FROM "Account" r WHERE r."id"="ForecastLine"."accountId"))) AND (("ForecastLine"."costCenterId" IS NULL OR EXISTS (SELECT 1 FROM "CostCenter" r WHERE r."id"="ForecastLine"."costCenterId"))) AND (("ForecastLine"."fiscalPeriodId" IS NULL OR EXISTS (SELECT 1 FROM "FiscalPeriod" r WHERE r."id"="ForecastLine"."fiscalPeriodId"))));

ALTER TABLE "ForecastComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ForecastComment" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ForecastComment" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ForecastComment" USING (EXISTS (SELECT 1 FROM "ForecastVersion" p WHERE p.id="ForecastComment"."forecastVersionId")) WITH CHECK ((EXISTS (SELECT 1 FROM "ForecastVersion" p WHERE p.id="ForecastComment"."forecastVersionId")) AND (("ForecastComment"."forecastVersionId" IS NULL OR EXISTS (SELECT 1 FROM "ForecastVersion" r WHERE r."id"="ForecastComment"."forecastVersionId"))) AND (("ForecastComment"."forecastLineId" IS NULL OR EXISTS (SELECT 1 FROM "ForecastLine" r WHERE r."id"="ForecastComment"."forecastLineId"))));

ALTER TABLE "OrganizationMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrganizationMembership" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "OrganizationMembership" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "OrganizationMembership" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("OrganizationMembership"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="OrganizationMembership"."organizationId"))));

ALTER TABLE "AuditEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditEvent" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "AuditEvent" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "AuditEvent" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("AuditEvent"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="AuditEvent"."organizationId"))));

ALTER TABLE "AgentRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgentRun" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "AgentRun" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "AgentRun" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("AgentRun"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="AgentRun"."organizationId"))) AND (("AgentRun"."forecastVersionId" IS NULL OR EXISTS (SELECT 1 FROM "ForecastVersion" r WHERE r."id"="AgentRun"."forecastVersionId"))));

ALTER TABLE "AgentRecommendation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgentRecommendation" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "AgentRecommendation" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "AgentRecommendation" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("AgentRecommendation"."runId" IS NULL OR EXISTS (SELECT 1 FROM "AgentRun" r WHERE r."id"="AgentRecommendation"."runId"))) AND (("AgentRecommendation"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="AgentRecommendation"."organizationId"))) AND (("AgentRecommendation"."forecastVersionId" IS NULL OR EXISTS (SELECT 1 FROM "ForecastVersion" r WHERE r."id"="AgentRecommendation"."forecastVersionId"))));

ALTER TABLE "AgentFeedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgentFeedback" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "AgentFeedback" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "AgentFeedback" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("AgentFeedback"."recommendationId" IS NULL OR EXISTS (SELECT 1 FROM "AgentRecommendation" r WHERE r."id"="AgentFeedback"."recommendationId"))) AND (("AgentFeedback"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="AgentFeedback"."organizationId"))));

ALTER TABLE "RuntimeExecution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RuntimeExecution" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "RuntimeExecution" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "RuntimeExecution" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("RuntimeExecution"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="RuntimeExecution"."organizationId"))) AND (("RuntimeExecution"."forecastVersionId" IS NULL OR EXISTS (SELECT 1 FROM "ForecastVersion" r WHERE r."id"="RuntimeExecution"."forecastVersionId"))));

ALTER TABLE "AccountingJournal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AccountingJournal" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "AccountingJournal" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "AccountingJournal" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("AccountingJournal"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="AccountingJournal"."organizationId"))) AND (("AccountingJournal"."legalEntityId" IS NULL OR EXISTS (SELECT 1 FROM "LegalEntity" r WHERE r."id"="AccountingJournal"."legalEntityId"))) AND (("AccountingJournal"."fiscalPeriodId" IS NULL OR EXISTS (SELECT 1 FROM "FiscalPeriod" r WHERE r."id"="AccountingJournal"."fiscalPeriodId"))));

ALTER TABLE "AccountingJournalLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AccountingJournalLine" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "AccountingJournalLine" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "AccountingJournalLine" USING (EXISTS (SELECT 1 FROM "AccountingJournal" p WHERE p.id="AccountingJournalLine"."journalId")) WITH CHECK ((EXISTS (SELECT 1 FROM "AccountingJournal" p WHERE p.id="AccountingJournalLine"."journalId")) AND (("AccountingJournalLine"."journalId" IS NULL OR EXISTS (SELECT 1 FROM "AccountingJournal" r WHERE r."id"="AccountingJournalLine"."journalId"))) AND (("AccountingJournalLine"."accountId" IS NULL OR EXISTS (SELECT 1 FROM "Account" r WHERE r."id"="AccountingJournalLine"."accountId"))));

ALTER TABLE "WorkflowRunRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkflowRunRecord" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "WorkflowRunRecord" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "WorkflowRunRecord" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("WorkflowRunRecord"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="WorkflowRunRecord"."organizationId"))));

ALTER TABLE "WorkflowExecutionRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkflowExecutionRecord" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "WorkflowExecutionRecord" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "WorkflowExecutionRecord" USING (EXISTS (SELECT 1 FROM "WorkflowRunRecord" p WHERE p.id="WorkflowExecutionRecord"."runId")) WITH CHECK ((EXISTS (SELECT 1 FROM "WorkflowRunRecord" p WHERE p.id="WorkflowExecutionRecord"."runId")) AND (("WorkflowExecutionRecord"."runId" IS NULL OR EXISTS (SELECT 1 FROM "WorkflowRunRecord" r WHERE r."id"="WorkflowExecutionRecord"."runId"))));

ALTER TABLE "Vendor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vendor" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "Vendor" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "Vendor" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("Vendor"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="Vendor"."organizationId"))));

ALTER TABLE "BankAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BankAccount" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "BankAccount" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "BankAccount" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("BankAccount"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="BankAccount"."organizationId"))) AND (("BankAccount"."legalEntityId" IS NULL OR EXISTS (SELECT 1 FROM "LegalEntity" r WHERE r."id"="BankAccount"."legalEntityId"))));

ALTER TABLE "BankTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BankTransaction" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "BankTransaction" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "BankTransaction" USING (EXISTS (SELECT 1 FROM "BankAccount" p WHERE p.id="BankTransaction"."bankAccountId")) WITH CHECK ((EXISTS (SELECT 1 FROM "BankAccount" p WHERE p.id="BankTransaction"."bankAccountId")) AND (("BankTransaction"."bankAccountId" IS NULL OR EXISTS (SELECT 1 FROM "BankAccount" r WHERE r."id"="BankTransaction"."bankAccountId"))) AND (("BankTransaction"."matchedJournalId" IS NULL OR EXISTS (SELECT 1 FROM "AccountingJournal" r WHERE r."id"="BankTransaction"."matchedJournalId"))));

ALTER TABLE "ApBill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApBill" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ApBill" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ApBill" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("ApBill"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="ApBill"."organizationId"))) AND (("ApBill"."legalEntityId" IS NULL OR EXISTS (SELECT 1 FROM "LegalEntity" r WHERE r."id"="ApBill"."legalEntityId"))) AND (("ApBill"."vendorId" IS NULL OR EXISTS (SELECT 1 FROM "Vendor" r WHERE r."id"="ApBill"."vendorId"))));

ALTER TABLE "ApPayment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApPayment" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ApPayment" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ApPayment" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("ApPayment"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="ApPayment"."organizationId"))) AND (("ApPayment"."legalEntityId" IS NULL OR EXISTS (SELECT 1 FROM "LegalEntity" r WHERE r."id"="ApPayment"."legalEntityId"))));

ALTER TABLE "ApPaymentAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApPaymentAllocation" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ApPaymentAllocation" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ApPaymentAllocation" USING (EXISTS (SELECT 1 FROM "ApPayment" p WHERE p.id="ApPaymentAllocation"."paymentId")) WITH CHECK ((EXISTS (SELECT 1 FROM "ApPayment" p WHERE p.id="ApPaymentAllocation"."paymentId")) AND (("ApPaymentAllocation"."paymentId" IS NULL OR EXISTS (SELECT 1 FROM "ApPayment" r WHERE r."id"="ApPaymentAllocation"."paymentId"))) AND (("ApPaymentAllocation"."billId" IS NULL OR EXISTS (SELECT 1 FROM "ApBill" r WHERE r."id"="ApPaymentAllocation"."billId"))));

ALTER TABLE "ArInvoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ArInvoice" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ArInvoice" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ArInvoice" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("ArInvoice"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="ArInvoice"."organizationId"))) AND (("ArInvoice"."legalEntityId" IS NULL OR EXISTS (SELECT 1 FROM "LegalEntity" r WHERE r."id"="ArInvoice"."legalEntityId"))) AND (("ArInvoice"."customerId" IS NULL OR EXISTS (SELECT 1 FROM "Customer" r WHERE r."id"="ArInvoice"."customerId"))));

ALTER TABLE "ArReceipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ArReceipt" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ArReceipt" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ArReceipt" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("ArReceipt"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="ArReceipt"."organizationId"))) AND (("ArReceipt"."legalEntityId" IS NULL OR EXISTS (SELECT 1 FROM "LegalEntity" r WHERE r."id"="ArReceipt"."legalEntityId"))));

ALTER TABLE "ArReceiptAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ArReceiptAllocation" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ArReceiptAllocation" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ArReceiptAllocation" USING (EXISTS (SELECT 1 FROM "ArReceipt" p WHERE p.id="ArReceiptAllocation"."receiptId")) WITH CHECK ((EXISTS (SELECT 1 FROM "ArReceipt" p WHERE p.id="ArReceiptAllocation"."receiptId")) AND (("ArReceiptAllocation"."receiptId" IS NULL OR EXISTS (SELECT 1 FROM "ArReceipt" r WHERE r."id"="ArReceiptAllocation"."receiptId"))) AND (("ArReceiptAllocation"."invoiceId" IS NULL OR EXISTS (SELECT 1 FROM "ArInvoice" r WHERE r."id"="ArReceiptAllocation"."invoiceId"))));

ALTER TABLE "ReportingFrameworkVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportingFrameworkVersion" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ReportingFrameworkVersion" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ReportingFrameworkVersion" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("ReportingFrameworkVersion"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="ReportingFrameworkVersion"."organizationId"))));

ALTER TABLE "ReportingRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportingRun" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ReportingRun" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ReportingRun" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("ReportingRun"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="ReportingRun"."organizationId"))) AND (("ReportingRun"."legalEntityId" IS NULL OR EXISTS (SELECT 1 FROM "LegalEntity" r WHERE r."id"="ReportingRun"."legalEntityId"))) AND (("ReportingRun"."fiscalPeriodId" IS NULL OR EXISTS (SELECT 1 FROM "FiscalPeriod" r WHERE r."id"="ReportingRun"."fiscalPeriodId"))) AND (("ReportingRun"."frameworkVersionId" IS NULL OR EXISTS (SELECT 1 FROM "ReportingFrameworkVersion" r WHERE r."id"="ReportingRun"."frameworkVersionId"))));

ALTER TABLE "ReportingDisclosureEvidence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportingDisclosureEvidence" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ReportingDisclosureEvidence" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ReportingDisclosureEvidence" USING (EXISTS (SELECT 1 FROM "ReportingRun" p WHERE p.id="ReportingDisclosureEvidence"."runId")) WITH CHECK ((EXISTS (SELECT 1 FROM "ReportingRun" p WHERE p.id="ReportingDisclosureEvidence"."runId")) AND (("ReportingDisclosureEvidence"."runId" IS NULL OR EXISTS (SELECT 1 FROM "ReportingRun" r WHERE r."id"="ReportingDisclosureEvidence"."runId"))));

ALTER TABLE "ReportingApproval" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportingApproval" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "ReportingApproval" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "ReportingApproval" USING (EXISTS (SELECT 1 FROM "ReportingRun" p WHERE p.id="ReportingApproval"."runId")) WITH CHECK ((EXISTS (SELECT 1 FROM "ReportingRun" p WHERE p.id="ReportingApproval"."runId")) AND (("ReportingApproval"."runId" IS NULL OR EXISTS (SELECT 1 FROM "ReportingRun" r WHERE r."id"="ReportingApproval"."runId"))));

ALTER TABLE "AccountingPostingApproval" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AccountingPostingApproval" FORCE ROW LEVEL SECURITY;
CREATE POLICY planora_maintenance ON "AccountingPostingApproval" TO CURRENT_USER USING (true) WITH CHECK (true);
CREATE POLICY planora_tenant ON "AccountingPostingApproval" USING ("organizationId" = planora_session_tenant()) WITH CHECK (("organizationId" = planora_session_tenant()) AND (("AccountingPostingApproval"."organizationId" IS NULL OR EXISTS (SELECT 1 FROM "Organization" r WHERE r."id"="AccountingPostingApproval"."organizationId"))) AND (("AccountingPostingApproval"."legalEntityId" IS NULL OR EXISTS (SELECT 1 FROM "LegalEntity" r WHERE r."id"="AccountingPostingApproval"."legalEntityId"))) AND (("AccountingPostingApproval"."fiscalPeriodId" IS NULL OR EXISTS (SELECT 1 FROM "FiscalPeriod" r WHERE r."id"="AccountingPostingApproval"."fiscalPeriodId"))) AND (("AccountingPostingApproval"."journalId" IS NULL OR EXISTS (SELECT 1 FROM "AccountingJournal" r WHERE r."id"="AccountingPostingApproval"."journalId"))));

COMMIT;
