import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowLeft, CheckCircle2, FileSpreadsheet, TableProperties } from "lucide-react";
import { requirePageSession } from "@/auth/session";
import { getTenantWorkbook } from "@/repositories/excel-repository";
import { prisma } from "@/lib/prisma";
import { AppError } from "@/lib/errors";
import { hasPermission } from "@/permissions/permissions";

type ProfileJson = { sheets: Array<{ name: string; state: string; usedRange: string; headerRow: number | null; headers: string[]; shape: string; formulaCount: number; duplicateHeaders: string[]; preview: Array<Array<string | number | boolean | null>> }> };
async function loadWorkbook(organizationId: string, id: string) { try { return await getTenantWorkbook(organizationId, id); } catch (error) { if (error instanceof AppError && error.code === "RESOURCE_NOT_FOUND") notFound(); throw error; } }
export default async function WorkbookPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ imported?: string; error?: string }> }) {
  const session = await requirePageSession(); const { id } = await params; const query = await searchParams;
  const workbook = await loadWorkbook(session.organization.id, id); const mapping = workbook.mappingVersions[0]; const profile = workbook.profile?.profile as unknown as ProfileJson;
  const accounts = await prisma.account.findMany({ where: { organizationId: session.organization.id, active: true }, select: { id: true, code: true, name: true }, orderBy: { code: "asc" } });
  const unresolved = mapping?.suggestions.filter((suggestion) => suggestion.status === "REVIEW_REQUIRED") ?? []; const batch = workbook.importBatches[0]; const primary = profile?.sheets.find((sheet) => ["p&l", "forecast"].includes(sheet.name.toLowerCase())) ?? profile?.sheets.find((sheet) => sheet.shape !== "UNKNOWN"); const concepts = ["ACCOUNT", "COST_CENTER", "PERIOD", "ACTUAL_AMOUNT", "FORECAST_AMOUNT"]; const canApproveMappings = hasPermission(session.membership.role, "mapping.approve");
  return <><Link className="back-link" href="/excel"><ArrowLeft size={16} />Excel imports</Link><div className="page-title-row"><div><h1 className="page-heading">{workbook.originalFileName}</h1><p className="subtle">Fingerprint {workbook.sha256.slice(0, 12)} · {(workbook.byteSize / 1024).toFixed(1)} KB</p></div><span className={`status ${workbook.status === "IMPORTED" ? "good" : ""}`}>{workbook.status.replaceAll("_", " ")}</span></div>
    {query.error && <div className="error-box" role="alert">{query.error}</div>}{query.imported && <div className="success-box" role="status"><CheckCircle2 size={17} />Canonical import completed with workbook lineage.</div>}
    <section className="profile-summary" aria-label="Workbook profile"><div><span>Sheets</span><strong>{workbook.profile?.sheetCount}</strong></div><div><span>Primary shape</span><strong>{workbook.profile?.primaryShape}</strong></div><div><span>Formulas</span><strong>{workbook.profile?.formulaCount}</strong></div><div><span>Hidden sheets</span><strong>{workbook.profile?.hiddenSheetCount}</strong></div></section>
    <section className="workspace-section"><div className="section-heading"><div><h2>Workbook inspection</h2><p>Detected structures and used ranges</p></div><TableProperties size={19} /></div><div className="sheet-grid">{profile?.sheets.map((sheet) => <div className="sheet-item" key={sheet.name}><div><FileSpreadsheet size={17} /><strong>{sheet.name}</strong></div><span>{sheet.shape} · {sheet.usedRange || "Empty"}</span><small>{sheet.headers.length ? sheet.headers.join(" · ") : "No header detected"}</small></div>)}</div></section>
    {primary && <section className="workspace-section"><div className="section-heading"><div><h2>Source preview</h2><p>First {primary.preview.length} data rows from {primary.name}</p></div></div><div className="preview-scroll"><table className="preview-table"><thead><tr>{primary.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{primary.preview.map((row, rowIndex) => <tr key={rowIndex}>{primary.headers.map((header, columnIndex) => <td key={header}>{String(row[columnIndex] ?? "")}</td>)}</tr>)}</tbody></table></div></section>}
    <section className="workspace-section"><div className="section-heading"><div><h2>Suggested mappings</h2><p>Column aliases and canonical account members</p></div><span className={`status ${unresolved.length ? "attention" : "good"}`}>{unresolved.length ? `${unresolved.length} NEEDS REVIEW` : "APPROVED"}</span></div>
      <div className="mapping-list">{mapping?.rules.map((rule) => <form className="mapping-row" action={`/api/excel/workbooks/${workbook.id}/mappings`} method="post" key={rule.id}><span>{rule.sourceField}</span><label>Canonical field<select name="targetConcept" defaultValue={rule.targetConcept}>{concepts.map((concept) => <option key={concept} value={concept}>{concept.replaceAll("_", " ")}</option>)}</select></label><input type="hidden" name="ruleId" value={rule.id} /><input type="hidden" name="reason" value="Human-reviewed field mapping" /><small>{Number(rule.confidence) * 100}% · {rule.reason}</small><button className="button button-secondary" type="submit">Save field mapping</button></form>)}</div>
      {mapping?.suggestions.map((suggestion) => <div className={`member-mapping ${suggestion.status === "REVIEW_REQUIRED" ? "review" : ""}`} key={suggestion.id}><div><span>Source account</span><strong>{suggestion.sourceValue}</strong><small>{suggestion.reason}</small></div>{suggestion.status === "REVIEW_REQUIRED" ? canApproveMappings ? <form action={`/api/excel/workbooks/${workbook.id}/mappings`} method="post"><input type="hidden" name="suggestionId" value={suggestion.id} /><input type="hidden" name="reason" value="Human-reviewed account correction" /><label>Canonical account<select required name="accountId" defaultValue=""><option disabled value="">Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></label><button className="button button-primary" type="submit">Approve correction</button></form> : <div className="mapping-approved" role="status"><AlertTriangle size={16} /><span>Director or CFO approval required</span></div> : <div className="mapping-approved"><CheckCircle2 size={16} /><span>{suggestion.decision ? "Human override" : "Matched"}</span></div>}</div>)}
    </section>
    {batch?.errors.length ? <section className="workspace-section"><div className="section-heading"><div><h2>Validation issues</h2><p>Blocking rows must be corrected before import.</p></div><AlertTriangle size={19} /></div>{batch.errors.map((error) => <div className="validation-row" key={error.id}><strong>{error.severity} · {error.code}</strong><span>Row {error.rowNumber}: {error.message}<small>{error.resolutionGuidance}</small></span><code>{error.sourceValue}</code></div>)}</section> : null}
    <section className="import-action"><div><h2>{workbook.status === "IMPORTED" ? "Canonical import complete" : "Validate and import"}</h2><p className="subtle">{workbook.status === "IMPORTED" ? `${batch?.rowCount ?? 0} rows imported with structured workbook, sheet, row, mapping-version, and batch lineage.` : "Validation checks required columns, members, periods, currency, scenario, amounts, and canonical grain."}</p>{batch?.resultMetrics && <div className="import-metrics"><span>Revenue <strong>${Number((batch.resultMetrics as Record<string, string>).REVENUE).toLocaleString()}</strong></span><span>EBITDA <strong>${Number((batch.resultMetrics as Record<string, string>).EBITDA).toLocaleString()}</strong></span></div>}</div>{workbook.status !== "IMPORTED" && <form action={`/api/excel/workbooks/${workbook.id}/import`} method="post"><button className="button button-primary" type="submit" disabled={unresolved.length > 0}>Validate and import</button></form>}</section>
  </>;
}
