services:
  postgres:
    image: postgres:18-alpine
    container_name: planora-postgres
    environment:
      POSTGRES_DB: planora
      POSTGRES_USER: planora
      POSTGRES_PASSWORD: planora_local_only
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planora -d planora"]
      interval: 2s
      timeout: 3s
      retries: 20
    volumes:
      - planora_postgres18_data:/var/lib/postgresql

volumes:
  planora_postgres18_data:
