import Link from "next/link";
import { requirePageSession } from "@/auth/session";
import { hasPermission } from "@/permissions/permissions";
import { managementDashboard } from "@/application/dashboard/dashboard-service";
import { formatMoney, formatPercent } from "@/domain/financial/money";

const labels: Record<string, string> = { REVENUE: "Revenue", OPERATING_EXPENSE: "Operating expense", EBITDA: "EBITDA / operating income" };
const currency = (value: string) => formatMoney(value);

export default async function DashboardPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await requirePageSession();
  if (!hasPermission(session.membership.role, "financial.read")) return <section className="panel" role="alert"><h1>403 — Dashboard unavailable</h1><p>Platform operations does not grant access to tenant financial data.</p></section>;
  const query = await searchParams;
  const value = (key: string) => typeof query[key] === "string" ? query[key] as string : undefined;
  const dashboard = await managementDashboard(session.organization.id, { cycle: value("cycle"), version: value("version") ? Number(value("version")) : undefined, period: value("period"), account: value("account"), costCenter: value("costCenter") });
  const detail = (title: string, rows: typeof dashboard.favorable, field: "variance" | "movement") => <section className="variance-panel"><h3>{title}</h3>{rows.length ? rows.map((row) => <Link className="variance-rank" key={row.id} href={`/forecasts/${dashboard.versionId}?search=${encodeURIComponent(row.accountCode)}&period=${row.periodCode}`}><span><strong>{row.accountName}</strong><small>{row.costCenterCode} · {row.periodCode}</small></span><b>{currency(row[field])}</b></Link>) : <p className="subtle">No matching records.</p>}</section>;
  return <>
    <div className="page-title-row"><div><h1 className="page-heading">Executive dashboard</h1><p className="subtle">{dashboard.cycleName} · version {dashboard.version}</p></div><span className="status good">{dashboard.status.replaceAll("_", " ")}</span></div>
    <form className="panel filter-bar" method="get" aria-label="Dashboard filters"><input name="cycle" defaultValue={dashboard.cycle} aria-label="Cycle"/><input name="version" type="number" min="1" defaultValue={dashboard.version} aria-label="Version"/><select name="period" defaultValue={value("period") ?? ""} aria-label="Period"><option value="">All periods</option>{dashboard.options.periods.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><select name="account" defaultValue={value("account") ?? ""} aria-label="Account"><option value="">All accounts</option>{dashboard.options.accounts.map(([code,name])=><option key={code} value={code}>{code} · {name}</option>)}</select><select name="costCenter" defaultValue={value("costCenter") ?? ""} aria-label="Cost center"><option value="">All cost centers</option>{dashboard.options.costCenters.map(([code,name])=><option key={code} value={code}>{code} · {name}</option>)}</select><button className="button" type="submit">Apply filters</button></form>
    <section className="metrics" aria-label="Executive KPI summary">{dashboard.kpis.map((kpi)=><div className="metric" data-testid={`kpi-${kpi.code}`} key={kpi.code}><div className="metric-label">{labels[kpi.code]}</div><div className="metric-value">{currency(kpi.current)}</div><div className="subtle">Actual {currency(kpi.actual)} · Prior {currency(kpi.prior)}</div><div className="subtle">Variance {currency(kpi.variance)} ({formatPercent(kpi.variancePct)}) · Movement {currency(kpi.movement)}</div></div>)}<div className="metric" data-testid="dashboard-forecast-total"><div className="metric-label">Forecast total</div><div className="metric-value">{currency(dashboard.forecastTotal)}</div><div className="subtle">{dashboard.recordCount} selected records</div></div><div className="metric"><div className="metric-label">Workflow</div><div className="metric-value">{dashboard.status}</div><div className="subtle">Approval {dashboard.approvedAt ? "approved" : "pending"} · Lock {dashboard.lockedAt ? "locked" : "open"}</div></div></section>
    <section className="variance-grid" aria-label="Variance intelligence">{detail("Top favorable variances", dashboard.favorable, "variance")}{detail("Top unfavorable variances", dashboard.unfavorable, "variance")}{detail("Largest forecast movements", dashboard.movements, "movement")}</section>
    <section className="panel"><div className="section-heading"><div><h2>Forecast trend</h2><p>Actual, prior forecast, and current forecast by period.</p></div></div><div className="table-scroll"><table><thead><tr><th>Period</th><th>Actual</th><th>Prior</th><th>Current</th></tr></thead><tbody>{dashboard.trend.map((row)=><tr key={row.periodCode}><td>{row.periodName}</td><td>{currency(row.actual)}</td><td>{currency(row.prior)}</td><td>{currency(row.current)}</td></tr>)}</tbody></table></div></section>
    <section className="variance-grid"><div className="variance-panel"><h3>Workflow health</h3>{Object.entries(dashboard.workflow).map(([status,count])=><div className="variance-rank" key={status}><span>{status.replaceAll("_"," ")}</span><b>{count}</b></div>)}</div><div className="variance-panel"><h3>Exceptions</h3>{Object.entries(dashboard.exceptions).map(([name,count])=><div className="variance-rank" key={name}><span>{name.replace(/([A-Z])/g," $1")}</span><b>{count}</b></div>)}</div><div className="variance-panel"><h3>Agent usage</h3><div className="variance-rank"><span>Recommendations</span><b>{dashboard.agents.generated}</b></div><div className="variance-rank"><span>Accepted / edited / rejected</span><b>{dashboard.agents.acceptancePct}% / {dashboard.agents.editPct}% / {dashboard.agents.rejectionPct}%</b></div><div className="variance-rank"><span>Failures / recoveries</span><b>{dashboard.agents.failures} / {dashboard.agents.recoveries}</b></div>{dashboard.agents.assistants.map((item)=><div className="variance-rank" key={`${item.assistant}-${item.version}`}><span>{item.assistant}</span><b>v{item.version}</b></div>)}<small>Usage metrics only; not evidence of financial correctness.</small></div></section>
    <section className="panel"><h2>Material variance records</h2><p className="subtle" data-testid="dashboard-record-count">{dashboard.material.length} material records · {dashboard.recordCount} selected records</p>{dashboard.material.slice(0,10).map((row)=><div className="audit-row" data-testid={`material-${row.accountCode}-${row.costCenterCode}`} key={row.id}><div><strong>{row.accountName}</strong><small>{row.costCenterName} · {row.periodName}</small></div><div>{currency(row.current)}</div><div className="material-variance">{currency(row.variance)}</div></div>)}</section>
  </>;
}
