-- Bank/AP/AR foundation. Hosted execution remains separately approved.
CREATE TYPE "SettlementStatus" AS ENUM ('OPEN','PARTIALLY_PAID','PAID','VOID');
CREATE TYPE "BankTransactionStatus" AS ENUM ('UNMATCHED','MATCHED','EXCLUDED');
CREATE TABLE "Vendor" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,UNIQUE("organizationId","code"));
CREATE TABLE "BankAccount" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT,"legalEntityId" UUID NOT NULL REFERENCES "LegalEntity"("id") ON DELETE RESTRICT,"name" TEXT NOT NULL,"currencyCode" CHAR(3) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE "BankTransaction" ("id" UUID PRIMARY KEY,"bankAccountId" UUID NOT NULL REFERENCES "BankAccount"("id") ON DELETE RESTRICT,"externalId" TEXT NOT NULL,"postedDate" DATE NOT NULL,"reference" TEXT NOT NULL,"amountMinor" BIGINT NOT NULL,"status" "BankTransactionStatus" NOT NULL DEFAULT 'UNMATCHED',"matchedJournalId" UUID REFERENCES "AccountingJournal"("id") ON DELETE RESTRICT,UNIQUE("bankAccountId","externalId"));
CREATE TABLE "ApBill" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT,"legalEntityId" UUID NOT NULL REFERENCES "LegalEntity"("id") ON DELETE RESTRICT,"vendorId" UUID NOT NULL REFERENCES "Vendor"("id") ON DELETE RESTRICT,"invoiceNumber" TEXT NOT NULL,"invoiceDate" DATE NOT NULL,"dueDate" DATE NOT NULL,"currencyCode" CHAR(3) NOT NULL,"totalMinor" BIGINT NOT NULL,"status" "SettlementStatus" NOT NULL DEFAULT 'OPEN',UNIQUE("organizationId","vendorId","invoiceNumber"));
CREATE TABLE "ApPayment" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT,"legalEntityId" UUID NOT NULL REFERENCES "LegalEntity"("id") ON DELETE RESTRICT,"currencyCode" CHAR(3) NOT NULL,"paidDate" DATE NOT NULL,"amountMinor" BIGINT NOT NULL,"reference" TEXT NOT NULL,UNIQUE("organizationId","reference"));
CREATE TABLE "ApPaymentAllocation" ("id" UUID PRIMARY KEY,"paymentId" UUID NOT NULL REFERENCES "ApPayment"("id") ON DELETE RESTRICT,"billId" UUID NOT NULL REFERENCES "ApBill"("id") ON DELETE RESTRICT,"amountMinor" BIGINT NOT NULL,UNIQUE("paymentId","billId"));
CREATE TABLE "ArInvoice" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT,"legalEntityId" UUID NOT NULL REFERENCES "LegalEntity"("id") ON DELETE RESTRICT,"customerId" UUID NOT NULL REFERENCES "Customer"("id") ON DELETE RESTRICT,"invoiceNumber" TEXT NOT NULL,"invoiceDate" DATE NOT NULL,"dueDate" DATE NOT NULL,"currencyCode" CHAR(3) NOT NULL,"totalMinor" BIGINT NOT NULL,"status" "SettlementStatus" NOT NULL DEFAULT 'OPEN',UNIQUE("organizationId","customerId","invoiceNumber"));
CREATE TABLE "ArReceipt" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT,"legalEntityId" UUID NOT NULL REFERENCES "LegalEntity"("id") ON DELETE RESTRICT,"currencyCode" CHAR(3) NOT NULL,"receivedDate" DATE NOT NULL,"amountMinor" BIGINT NOT NULL,"reference" TEXT NOT NULL,UNIQUE("organizationId","reference"));
CREATE TABLE "ArReceiptAllocation" ("id" UUID PRIMARY KEY,"receiptId" UUID NOT NULL REFERENCES "ArReceipt"("id") ON DELETE RESTRICT,"invoiceId" UUID NOT NULL REFERENCES "ArInvoice"("id") ON DELETE RESTRICT,"amountMinor" BIGINT NOT NULL,UNIQUE("receiptId","invoiceId"));
CREATE INDEX "BankAccount_scope_idx" ON "BankAccount"("organizationId","legalEntityId");
CREATE INDEX "BankTransaction_close_idx" ON "BankTransaction"("bankAccountId","postedDate","status");
CREATE INDEX "ApBill_close_idx" ON "ApBill"("organizationId","legalEntityId","dueDate","status");
CREATE INDEX "ArInvoice_close_idx" ON "ArInvoice"("organizationId","legalEntityId","dueDate","status");
