import ExcelJS from "exceljs";
import { requireApiSession } from "@/auth/session";
import { writeAudit } from "@/audit/audit";
import { forecastWorkspace } from "@/application/forecast/forecast-service";
import { AppError, errorResponse } from "@/lib/errors";
import { correlationId } from "@/lib/request";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
export async function GET(request: Request,{params}:{params:Promise<{id:string}>}){const cid=correlationId(request);try{const session=await requireApiSession("forecast.export");const id=z.uuid().parse((await params).id);const workspace=await forecastWorkspace(session.organization.id,id,{all:true});if(!["APPROVED","LOCKED"].includes(workspace.version.status))throw new AppError("CONFLICT","Only approved or locked forecasts can be exported.",409);const format=new URL(request.url).searchParams.get("format")==="csv"?"csv":"xlsx";const headers=["Cycle","Version","Period","Account","Cost Center","Actual","Prior Forecast","Current Forecast","Variance","Variance %","Commentary"];const rows=workspace.lines.map(l=>[workspace.version.forecast.name,workspace.version.version,l.fiscalPeriod.code,l.account.code,l.costCenter.code,l.actual,l.prior,l.current,l.variance,l.variancePct,l.comments[0]?.body??""]);let body:BodyInit;let contentType:string;let extension:string;if(format==="csv"){body=[headers,...rows].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\r\n");contentType="text/csv; charset=utf-8";extension="csv";}else{const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet("Forecast");sheet.addRow(headers);rows.forEach(row=>sheet.addRow(row));sheet.getRow(1).font={bold:true};sheet.columns.forEach((column,index)=>{column.width=index<5?20:16;});body=Buffer.from(await workbook.xlsx.writeBuffer());contentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";extension="xlsx";}await writeAudit(prisma,{organizationId:session.organization.id,actorId:session.user.id,action:"FORECAST.EXPORTED",entityType:"ForecastVersion",entityId:id,newState:{format,rowCount:rows.length},correlationId:cid});return new Response(body,{headers:{"Content-Type":contentType,"Content-Disposition":`attachment; filename="FY26_Forecast_V${workspace.version.version}.${extension}"`}});}catch(error){return errorResponse(error,cid);}}
