import { Download } from "lucide-react";
import { notFound } from "next/navigation";
import { requirePageSession } from "@/auth/session";
import { forecastWorkspace } from "@/application/forecast/forecast-service";
import { formatMoney, formatPercent } from "@/domain/financial/money";
import { prisma } from "@/lib/prisma";
import { AppError } from "@/lib/errors";
import { listForecastRecommendations } from "@/agents/agent-service";

const actionsByState: Record<string, Record<string, Array<[string, string]>>> = {
  DRAFT: { ANALYST: [["submit", "Submit forecast"]], FPA_DIRECTOR: [["submit", "Submit forecast"]], CFO: [["submit", "Submit forecast"]] },
  REVISION_REQUIRED: { ANALYST: [["submit", "Resubmit forecast"]], FPA_DIRECTOR: [["submit", "Resubmit forecast"]], CFO: [["submit", "Resubmit forecast"]] },
  SUBMITTED: { FPA_DIRECTOR: [["review", "Begin review"]], CFO: [["review", "Begin review"]] },
  IN_REVIEW: { FPA_DIRECTOR: [["revise", "Request revision"], ["approve", "Approve forecast"]], CFO: [["revise", "Request revision"], ["approve", "Approve forecast"]] },
  APPROVED: { CFO: [["lock", "Lock forecast"]] },
};
async function loadWorkspace(organizationId: string, id: string, query: { search?: string; period?: string; page?: string }) { try { return await forecastWorkspace(organizationId, id, query); } catch (error) { if (error instanceof AppError && error.code === "RESOURCE_NOT_FOUND") notFound(); throw error; } }

export default async function ForecastPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ search?: string; period?: string; page?: string; error?: string; agentRun?: string; agentDecision?: string }> }) {
  const session = await requirePageSession(); const { id } = await params; const query = await searchParams;
  const workspace = await loadWorkspace(session.organization.id, id, query);
  const periods = [...new Map(workspace.version.lines.map((line) => [line.fiscalPeriod.id, line.fiscalPeriod])).values()];
  const audits = await prisma.auditEvent.findMany({ where: { organizationId: session.organization.id, OR: [{ entityId: id }, { metadata: { path: ["forecastVersionId"], equals: id } }] }, orderBy: { occurredAt: "desc" }, take: 40, include: { actor: true } });
  const recommendations = await listForecastRecommendations(session.organization.id, id);
  const byType = (type: string) => workspace.version.lines.filter((line) => line.account.type === type).reduce((sum, line) => sum + Number(line.currentForecast), 0);
  const revenue = byType("REVENUE"); const cogs = byType("COGS"); const opex = byType("OPERATING_EXPENSE"); const ebitda = revenue - cogs - opex;
  const workflowActions = actionsByState[workspace.version.status]?.[session.membership.role] ?? [];
  const canExport = ["APPROVED", "LOCKED"].includes(workspace.version.status);
  const ranking = (title: string, rows: typeof workspace.lines) => <section className="variance-panel"><h3>{title}</h3>{rows.map((line) => <div className="variance-rank" key={`${title}-${line.id}`}><span><strong>{line.account.name}</strong><small>{line.costCenter.code} · {line.fiscalPeriod.code}</small></span><b>{title === "Largest movements" ? formatMoney(line.movement) : formatMoney(line.variance)}</b></div>)}</section>;
  return <>
    <div className="page-title-row"><div><h1 className="page-heading">{workspace.version.forecast.name}</h1><p className="subtle">Version {workspace.version.version} · Actual, prior forecast, current forecast, and governed commentary</p></div><span className={`status ${canExport ? "good" : ""}`}>{workspace.version.status.replaceAll("_", " ")}</span></div>
    {query.error && <div className="error-box" role="alert">{query.error}</div>}
    <section className="metrics" aria-label="Management forecast summary"><div className="metric"><div className="metric-label">Revenue</div><div className="metric-value">{formatMoney(revenue, "USD", true)}</div></div><div className="metric"><div className="metric-label">Operating expense</div><div className="metric-value">{formatMoney(opex, "USD", true)}</div></div><div className="metric"><div className="metric-label">EBITDA</div><div className="metric-value">{formatMoney(ebitda, "USD", true)}</div></div><div className="metric"><div className="metric-label">Approval state</div><div className="metric-value metric-status">{workspace.version.status.replaceAll("_", " ")}</div></div></section>
    <div className="variance-grid">{ranking("Top favorable", workspace.topFavorable)}{ranking("Top unfavorable", workspace.topUnfavorable)}{ranking("Largest movements", workspace.largestMovements)}</div>
    <form className="filter-bar" method="get"><label className="compact-field">Search<input name="search" defaultValue={query.search ?? ""} placeholder="Account or cost center" /></label><label className="compact-field">Period<select name="period" defaultValue={query.period ?? ""}><option value="">All periods</option>{periods.map((period) => <option key={period.id} value={period.id}>{period.name}</option>)}</select></label><button className="button button-secondary">Apply</button></form>
    <section className="forecast-table" role="table"><div className="forecast-row forecast-head" role="row"><span>Account / Cost center</span><span>Actual</span><span>Prior</span><span>Current</span><span>Variance</span><span>Variance %</span></div>{workspace.lines.map((line) => <div className="forecast-row" role="row" key={line.id}><span><strong>{line.account.name}</strong><small>{line.costCenter.name} · {line.fiscalPeriod.code}</small></span><span>{formatMoney(line.actual)}</span><span>{formatMoney(line.prior)}</span><span>{workspace.editable ? <form action={`/api/forecasts/${id}/lines/${line.id}`} method="post"><input aria-label={`Current forecast for ${line.account.name} ${line.costCenter.code}`} name="currentForecast" defaultValue={line.current} /><input type="hidden" name="reason" value="Analyst forecast update" /><button className="button button-secondary">Save</button></form> : formatMoney(line.current)}</span><span>{formatMoney(line.variance)}</span><span>{formatPercent(line.variancePct)}</span></div>)}</section>
    <nav className="pagination" aria-label="Forecast pages"><span>{workspace.totalLines} lines · Page {workspace.page} of {workspace.pageCount}</span>{workspace.page > 1 && <a className="button button-secondary" href={`?search=${encodeURIComponent(query.search ?? "")}&period=${encodeURIComponent(query.period ?? "")}&page=${workspace.page - 1}`}>Previous</a>}{workspace.page < workspace.pageCount && <a className="button button-secondary" href={`?search=${encodeURIComponent(query.search ?? "")}&period=${encodeURIComponent(query.period ?? "")}&page=${workspace.page + 1}`}>Next</a>}</nav>
    <section className="workspace-section agent-panel" id="assistants"><div className="section-heading"><div><h2>Governed assistants</h2><p>Deterministic recommendations grounded in this tenant and version. Assistants cannot approve, lock, bypass validation, or change financial data.</p></div><span className="status good">HUMAN CONTROLLED</span></div><div className="agent-launchers">
      <form action="/api/agents/run" method="post"><input type="hidden" name="agentId" value="PLANORA.WORKFLOW.ASSISTANT.NEXT_ACTION.v1" /><input type="hidden" name="forecastVersionId" value={id} /><input type="hidden" name="task" value="What should I do next?" /><button className="button button-secondary">What should I do next?</button></form>
      <form action="/api/agents/run" method="post"><input type="hidden" name="agentId" value="PLANORA.FORECAST.ANALYST.VARIANCE.v1" /><input type="hidden" name="forecastVersionId" value={id} /><input type="hidden" name="task" value="Show largest forecast movements" /><button className="button button-secondary">Show largest movements</button></form>
      <form action="/api/agents/run" method="post"><input type="hidden" name="agentId" value="PLANORA.FORECAST.ANALYST.COMMENTARY.v1" /><input type="hidden" name="forecastVersionId" value={id} /><input type="hidden" name="task" value="Draft supported commentary" /><button className="button button-secondary">Draft commentary</button></form>
      {session.membership.role !== "ANALYST" && <form action="/api/agents/run" method="post"><input type="hidden" name="agentId" value="PLANORA.REVIEW.DIRECTOR.EXCEPTION.v1" /><input type="hidden" name="forecastVersionId" value={id} /><input type="hidden" name="task" value="What requires my attention?" /><button className="button button-secondary">What requires attention?</button></form>}
    </div>{query.agentDecision && <p className="agent-notice">Recommendation decision recorded: {query.agentDecision}. Live agent behavior was not changed.</p>}<div className="agent-results">{recommendations.length === 0 && <p className="subtle">No assistant runs for this version yet.</p>}{recommendations.map((recommendation) => <article className="agent-result" key={recommendation.id}><header><span><strong>{recommendation.run.agentDefinition.displayName}</strong><small>{recommendation.run.agentDefinition.agentId}</small></span><span className={`status ${recommendation.status === "PENDING" ? "attention" : "good"}`}>{recommendation.status}</span></header><h3>{recommendation.summary}</h3>{recommendation.proposedContent && <p className="agent-content">{recommendation.proposedContent}</p>}<p className="agent-evidence">Evidence: canonical forecast version {workspace.version.version}, persisted calculations, {((recommendation.evidence as { references?: unknown[] }).references ?? []).length} traceable reference(s). Unsupported claims: {recommendation.unsupportedClaim ? "present" : "none"}.</p>{recommendation.status === "PENDING" && <div className="agent-decisions"><form action={`/api/agent-recommendations/${recommendation.id}/feedback`} method="post"><input type="hidden" name="forecastVersionId" value={id} /><input type="hidden" name="decision" value="ACCEPTED" /><input type="hidden" name="reason" value="Accepted after human review" /><button className="button button-secondary">Accept</button></form>{recommendation.type === "COMMENTARY_DRAFT" && <form className="agent-edit" action={`/api/agent-recommendations/${recommendation.id}/feedback`} method="post"><input type="hidden" name="forecastVersionId" value={id} /><input type="hidden" name="decision" value="EDITED" /><input type="hidden" name="reason" value="Edited after human review" /><textarea aria-label={`Edit ${recommendation.run.agentDefinition.displayName} suggestion`} name="finalContent" required defaultValue={recommendation.proposedContent ?? ""} /><button className="button button-secondary">Save edited</button></form>}<form action={`/api/agent-recommendations/${recommendation.id}/feedback`} method="post"><input type="hidden" name="forecastVersionId" value={id} /><input type="hidden" name="decision" value="REJECTED" /><input type="hidden" name="reason" value="Rejected after human review" /><button className="button button-secondary">Reject</button></form></div>}</article>)}</div></section>
    <section className="forecast-bottom"><div className="workspace-section"><div className="section-heading"><div><h2>Commentary</h2><p>Version-scoped financial context</p></div></div>{["DRAFT", "REVISION_REQUIRED", "IN_REVIEW"].includes(workspace.version.status) && <form className="comment-form" action={`/api/forecasts/${id}/comments`} method="post"><textarea aria-label="Forecast commentary" name="body" required minLength={3} placeholder="Explain the material variance using supported facts." /><button className="button button-secondary">Add commentary</button></form>}{workspace.version.comments.map((comment) => <div className="comment" key={comment.id}><strong>{comment.author.name}</strong><span>{comment.createdAt.toISOString().slice(0, 16).replace("T", " ")} UTC</span><p>{comment.body}</p></div>)}</div>
      <div className="workspace-section"><div className="section-heading"><div><h2>Workflow</h2><p>Outstanding action: {workflowActions[0]?.[1] ?? (workspace.version.status === "LOCKED" ? "None - finalized" : "Waiting for authorized reviewer")}</p></div></div>{workflowActions.map(([action, label]) => <form className="workflow-action" key={action} action={`/api/forecasts/${id}/transition`} method="post"><input type="hidden" name="action" value={action} /><input type="hidden" name="idempotencyKey" value={`${id}:${action}:${workspace.version.updatedAt.toISOString()}`} /><input aria-label={`${label} reason`} name="reason" required minLength={3} placeholder={`${label} reason`} /><button className="button button-primary">{label}</button></form>)}{canExport && <div className="export-actions"><a className="button button-secondary" href={`/api/forecasts/${id}/export`}><Download size={16} />Export XLSX</a><a className="button button-secondary" href={`/api/forecasts/${id}/export?format=csv`}><Download size={16} />Export CSV</a></div>}</div></section>
    <section className="workspace-section"><div className="section-heading"><div><h2>Audit history</h2><p>Who changed what, when, and in this version</p></div></div>{audits.map((audit) => <div className="audit-row" key={audit.id}><strong>{audit.action}</strong><span>{audit.actor?.name ?? "System"}</span><time>{audit.occurredAt.toISOString()}</time></div>)}</section>
  </>;
}
