"use client";
import { useState } from "react";
export function CoaMappingEditor({account}:{account:{id:string;statementClass:string|null;statementSection:string|null;reportingCode:string|null;cashFlowClass:string|null;systemPurpose:string;suspenseAllowed:boolean}}){
 const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 return <form onSubmit={async e=>{e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);const body={accountId:account.id,statementClass:fd.get("statementClass"),statementSection:fd.get("statementSection"),reportingCode:fd.get("reportingCode"),cashFlowClass:fd.get("cashFlowClass"),systemPurpose:fd.get("systemPurpose"),suspenseAllowed:fd.get("suspenseAllowed")==="on"};const r=await fetch("/api/accounting/chart-of-accounts/mapping",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setMessage(r.ok?"Saved · "+d.correlationId:d.error??"Save failed");setBusy(false);if(r.ok)location.reload();}} className="filter-bar">
 <select name="statementClass" defaultValue={account.statementClass??"PROFIT_AND_LOSS"}><option value="PROFIT_AND_LOSS">P&amp;L</option><option value="BALANCE_SHEET">Balance Sheet</option><option value="STATISTICAL">Statistical</option></select>
 <input name="statementSection" defaultValue={account.statementSection??""} placeholder="Statement section" required/><input name="reportingCode" defaultValue={account.reportingCode??""} placeholder="Reporting code" required/>
 <select name="cashFlowClass" defaultValue={account.cashFlowClass??"NOT_APPLICABLE"}><option value="OPERATING">Operating</option><option value="INVESTING">Investing</option><option value="FINANCING">Financing</option><option value="CASH">Cash</option><option value="NOT_APPLICABLE">N/A</option></select>
 <select name="systemPurpose" defaultValue={account.systemPurpose}><option value="NONE">None</option><option value="CASH">Cash</option><option value="ACCOUNTS_RECEIVABLE">AR</option><option value="ACCOUNTS_PAYABLE">AP</option><option value="RETAINED_EARNINGS">Retained earnings</option><option value="SUSPENSE">Suspense</option></select>
 <label><input type="checkbox" name="suspenseAllowed" defaultChecked={account.suspenseAllowed}/> Suspense allowed</label><button className="button button-secondary" disabled={busy}>{busy?"Saving...":"Save mapping"}</button>{message&&<span role="status">{message}</span>}</form>;
}
