import { requirePageSession } from "@/auth/session";
import { platformOverview } from "@/application/platform-admin/platform-admin-service";

export default async function PlatformAdminPage() {
  const session = await requirePageSession();
  if (session.membership.role !== "PLATFORM_ADMIN") return <section className="panel" role="alert"><h1>403 — Platform administration unavailable</h1><p>This surface requires the separate Platform Admin role.</p></section>;
  const data = await platformOverview({ role: session.membership.role, actorId: session.user.id, auditOrganizationId: session.organization.id, correlationId: `page-${session.sessionId}` });
  const pilots = data.organizations.filter((org) => org.pilot);
  return <>
    <div className="page-title-row"><div><h1 className="page-heading">Platform administration</h1><p className="subtle">Bounded pilot operations; no tenant financial authority.</p></div><span className="status good">PLATFORM ADMIN</span></div>
    <section id="health" className="metrics" aria-label="Platform health"><div className="metric"><div className="metric-label">App / database</div><div className="metric-value">{data.health.app}</div><div className="subtle">DB {data.health.database}</div></div><div className="metric"><div className="metric-label">Pilot ready</div><div className="metric-value">{data.health.pilotReady}</div><div className="subtle">Tenants with roles and forecast</div></div><div className="metric"><div className="metric-label">Operational failures</div><div className="metric-value">{data.health.failedImports + data.health.failedRuntime}</div><div className="subtle">Imports {data.health.failedImports} · runtime {data.health.failedRuntime} · exports {data.health.failedExports}</div></div><div className="metric"><div className="metric-label">Migration readiness</div><div className="metric-value">Ready</div><div className="subtle">{data.health.migration}</div></div></section>
    <section id="organizations" className="panel"><div className="section-heading"><div><h2>Organizations</h2><p>Create and prepare synthetic pilot tenants only.</p></div></div><form action="/api/platform-admin" method="post" className="filter-bar"><input type="hidden" name="action" value="create-organization"/><input required name="code" placeholder="PILOT-CODE" aria-label="Organization code"/><input required name="name" placeholder="Pilot organization name" aria-label="Organization name"/><button className="button" type="submit">Create pilot</button></form><div className="workbook-list">{data.organizations.map((org)=><div className="workbook-row" key={org.id}><span><strong>{org.name}</strong><small>{org.code} · {org._count.memberships} members · {org._count.forecasts} forecasts</small></span><span className={`status ${org.active ? "good" : ""}`}>{org.pilot ? `PILOT · ${org.active ? "ACTIVE" : "INACTIVE"}` : "NON-PILOT"}</span>{org.pilot ? <><form action="/api/platform-admin" method="post"><input type="hidden" name="action" value="set-organization-active"/><input type="hidden" name="organizationId" value={org.id}/><input type="hidden" name="active" value={org.active ? "false" : "true"}/><button className="button button-secondary" type="submit">{org.active ? "Deactivate" : "Activate"}</button></form><form action="/api/platform-admin" method="post"><input type="hidden" name="action" value="prepare-pilot"/><input type="hidden" name="organizationId" value={org.id}/><button className="button button-secondary" type="submit">Prepare/reset</button></form></> : null}</div>)}</div></section>
    <section id="memberships" className="panel"><div className="section-heading"><div><h2>Memberships</h2><p>Financial roles remain tenant-scoped and separate from platform authority.</p></div></div><form action="/api/platform-admin" method="post" className="filter-bar"><input type="hidden" name="action" value="upsert-membership"/><select required name="organizationId" aria-label="Pilot organization">{pilots.map((org)=><option key={org.id} value={org.id}>{org.name}</option>)}</select><input required name="name" placeholder="Name"/><input required type="email" name="email" placeholder="pilot@example.test"/><select name="role"><option value="ANALYST">Analyst</option><option value="FPA_DIRECTOR">FP&amp;A Director</option><option value="CFO">CFO</option></select><button className="button" type="submit">Add or update</button></form>{data.memberships.map((member)=><div className="audit-row" key={member.id}><div><strong>{member.user.name}</strong><small>{member.user.email} · {member.organization.name}</small></div><div>{member.role.replace("FPA_","FP&A ")}</div><form action="/api/platform-admin" method="post"><input type="hidden" name="action" value="deactivate-membership"/><input type="hidden" name="membershipId" value={member.id}/><button disabled={!member.organization.pilot || !member.active} className="button button-secondary" type="submit">{member.active ? "Deactivate" : "Inactive"}</button></form></div>)}</section>
    <section id="agents" className="panel"><div className="section-heading"><div><h2>Agent controls</h2><p>Operational state cannot grant financial write, approval, or lock authority.</p></div></div>{data.agents.map((agent)=><div className="audit-row" key={agent.id}><div><strong>{agent.displayName}</strong><small>{agent.agentId} · v{agent.version}</small></div><div>{agent.killSwitch}</div><form action="/api/platform-admin" method="post" className="filter-bar"><input type="hidden" name="action" value="set-agent-state"/><input type="hidden" name="agentId" value={agent.id}/><select name="state" defaultValue={agent.killSwitch}><option>ENABLED</option><option>READ_ONLY</option><option>DISABLED</option></select><button className="button button-secondary" type="submit">Change</button></form></div>)}</section>
    <section id="audit" className="panel"><div className="section-heading"><div><h2>Platform audit</h2><p>Operational metadata only; tenant financial payloads are excluded.</p></div></div>{data.audit.map((event)=><div className="audit-row" key={event.id}><div><strong>{event.action}</strong><small>{event.organization.code} · {event.entityType}</small></div><div>{event.actor?.name ?? "system"}</div><div><small>{event.correlationId}</small>{event.occurredAt.toISOString()}</div></div>)}</section>
    <section className="panel"><h2>Support boundary</h2><p>Platform support may manage pilot tenancy, memberships, operational agent state, and safe health metadata. It cannot view or change tenant forecasts, submit, approve, lock, bypass validation, impersonate users, or mutate audit evidence.</p></section>
  </>;
}
